# Generated by Django 3.2.16 on 2022-12-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Unresolved', 'Unresolved'), ('Resolver', 'Resolved'), ('Frozen', 'Frozen')], default='Unresolved', max_length=10)),
                ('feedback', models.CharField(max_length=255)),
            ],
        ),
    ]
