# Generated by Django 3.2.16 on 2022-12-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='feedback',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
